kind: "Service"
apiVersion: "v1"
metadata:
  name: "hawtio-springboot"
spec:
  ports:
    -
      name: "jolokia"
      protocol: "TCP"
      port: 8081 
      targetPort: 8778 
      nodePort: 0
selector:
  app: s2i-spring-boot-cxf-jaxrs
