apiVersion: v1
kind: Service
metadata:
  name: fis-cxfrs      
spec:
  selector:                  
    app: s2i-spring-boot-cxf-jaxrs
  ports:
  - nodePort: 0
    port: 9080               
    protocol: TCP
    targetPort: 8080