apiVersion: v1
kind: Service
metadata:
  name: account-service      
spec:
  selector:                  
    app: account-app
  ports:
  - nodePort: 0
    port: 9080               
    protocol: TCP
    targetPort: 8080